apiVersion: sts.silicom.com/v1alpha1
kind: StsOperatorConfig
metadata:
  name: sts-operator-config
spec:
  namespace: sts-silicom
  grpcSvcPort: 50051
  gpsSvcPort: 2947
  images:
    tsyncd: quay.io/silicom/tsyncd:2.1.0.0
    ts2Phcs: quay.io/silicom/ts2phcs:1.0.0
    phcs2Sys: quay.io/silicom/phcs2sys:3.1.1
    grpcTsyncd: quay.io/silicom/grpc-tsyncd:2.1.0.0
    stsPlugin: quay.io/silicom/sts-plugin:0.0.1
    gpsd: quay.io/silicom/gpsd:3.23.1
  sro:
    namespace: openshift-operators
    iceVersion: 1.7.16
    srcImage: quay.io/silicom/ice-driver-src:1.7.16
    srcSvcPort: 3000
    chart:
      repository:
        url: http://ice-driver-src
        name: ice-special-resource
      name: ice-special-resource
      version: 0.0.1
