apiVersion: sts.silicom.com/v1alpha1
kind: StsConfig
metadata:
  name: gm-1
  namespace: sts-silicom
spec:
  namespace: sts-silicom
  imageRegistry: quay.io/silicom
  nodeSelector:
    sts.silicom.com/config: "gm-1"
  stsVersion: 2.0.1.1
  mode: T-GM.8275.1
  interfaces:
    - ethName: enp2s0f0
      synce: 1
      holdoff: 500
      mode: Master
      ethPort: 0
    - ethName: enp2s0f1
      synce: 1
      holdoff: 500
      mode: Master
      ethPort: 1
