apiVersion: sts.silicom.com/v1alpha1
kind: StsConfig
metadata:
  name: gm-1
spec:
  name: gm-1
  nodeSelector:
    mode.sts.silicom.com/gm-1: ""
  mode: gm
  namespace: gm-1
  interfaces:
    - ethName: enp2s0f0
      synce: true
      holdoff: 500
    - ethName: enp2s0f1
      synce: true
      holdoff: 500

